<?php

return [
    'menu' => [
        [
            'id' => 'menu-dashboard',
            'title' => 'Dashboard',
            'icon' => '<i class="fas nav-icon fa-chart-line"></i>',
            'href' => '/dashboard',
            'permissions' => ['view_report'],
            'children' => [],
        ],
        [
            'id' => 'menu-account',
            'title' => 'Accounts',
            'icon' => '<i class="nav-icon  nav-icon fas fa-user"></i>',
            'href' => '',
            'permissions' => ['super_admin'],
            'children' => [
                [
                    'id' => 'menu-user',
                    'title' => 'Users',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/user',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'menu-role',
                    'title' => 'Roles',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/role',
                    'permissions' => [],
                    'children' => [],
                ],
            ],
        ],
        [
            'id' => 'menu-config',
            'title' => 'Configs',
            'icon' => '<i class="nav-icon fas fa-cog"></i>',
            'href' => '',
            'permissions' => ['config_manage'],
            'children' => [
                [
                    'id' => 'config-system',
                    'title' => 'System',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/config-system',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'config-website',
                    'title' => 'Website',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/config-website',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'config-lang',
                    'title' => 'Lang',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/configlang',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'config-widget',
                    'title' => 'Widget',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/config-widget',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'config-icon',
                    'title' => 'Icons',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/config-icon',
                    'permissions' => [],
                    'children' => [],
                ],

            ],
        ],
        [
            'id' => 'menu-manager',
            'title' => 'Menus',
            'icon' => '<i class="nav-icon fas fa-bars"></i>',
            'href' => '',
            'permissions' => ['menu_manage'],
            'children' => [
                [
                    'id' => 'menugroup',
                    'title' => 'Menu Group',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/menugroup',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'menu-menu',
                    'title' => 'Menu',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/menu',
                    'permissions' => [],
                    'children' => [],
                ],

            ],
        ],
        [
            'id' => 'menu-resource',
            'title' => 'Resources',
            'icon' => '<i class="nav-icon fas fa-database"></i>',
            'href' => '',
            'permissions' => [],
            'children' => [
                [
                    'id' => 'albumgroup',
                    'title' => 'Album',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/albumgroup',
                    'permissions' => ['album_manage'],
                    'children' => [],
                ],
                [
                    'id' => 'videogroup',
                    'title' => 'Video',
                    'icon' => 'fa-video-o',
                    'href' => '/admin/videogroup',
                    'permissions' => ['video_manage'],
                    'children' => [],
                ],
                [
                    'id' => 'questiongroup',
                    'title' => 'Question',
                    'icon' => 'fa-video-o',
                    'href' => '/admin/questiongroup',
                    'permissions' => ['question_manage'],
                    'children' => [],
                ],
                [
                    'id' => 'customeridea',
                    'title' => 'Customer Idea',
                    'icon' => 'fa-video-o',
                    'href' => '/admin/customeridea',
                    'permissions' => ['customeridea_manage'],
                    'children' => [],
                ],
            ],
        ],
        [
            'id' => 'menu-posts',
            'title' => 'Posts',
            'icon' => '<i class="nav-icon fas fa-newspaper"></i>',
            'href' => '',
            'permissions' => ['post_manage'],
            'children' => [
                [
                    'id' => 'category',
                    'title' => 'Categories',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/category',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'all-post',
                    'title' => 'All Post',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/post',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'menu-tag',
                    'title' => 'Tags',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/tag',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'menu-comment',
                    'title' => 'Comments',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/comment',
                    'permissions' => [],
                    'children' => [],
                ],
            ],
        ],
        [
            'id' => 'menu-recruitment',
            'title' => 'Recruitment',
            'icon' => '<i class="nav-icon fas fa-address-book"></i>',
            'href' => '/admin/recruitment',
            'permissions' => ['post_manage'],
            'children' => [],
        ],
        [
            'id' => 'menu-project',
            'title' => 'Build Project',
            'icon' => '<i class="nav-icon fas fa-cube"></i>',
            'href' => '',
            'permissions' => ['post_manage'],
            'children' => [
                [
                    'id' => '',
                    'title' => 'Group',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/buildprojectgroup',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => '',
                    'title' => 'Projects',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/buildproject',
                    'permissions' => [],
                    'children' => [],
                ],

            ],
        ],
        [
            'id' => 'menu-contact',
            'title' => 'Contacts',
            'icon' => '<i class="nav-icon fas fa-download"></i>',
            'href' => '/admin/receive',
            'permissions' => ['receive_manage'],
            'children' => [],
        ],
        [
            'id' => 'menu-order',
            'title' => 'Orders',
            'icon' => '<i class="nav-icon fas fa-shopping-bag"></i>',
            'href' => '/admin/order',
            'permissions' => ['order_manage'],
            'children' => [],
        ],
        [
            'id' => 'menu-product',
            'title' => 'Products',
            'icon' => '<i class="nav-icon fas fa-gavel"></i>',
            'href' => '',
            'permissions' => ['product_manage'],
            'children' => [
                [
                    'id' => 'productgroup',
                    'title' => 'CategoriesProduct',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/productgroup',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'menu-brand',
                    'title' => 'Brand',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/brand',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'menu-product',
                    'title' => 'All Product',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/product',
                    'permissions' => [],
                    'children' => [],
                ],

            ],
        ],
        [
            'id' => 'menu-drugstore',
            'title' => 'Drugstores',
            'icon' => '<i class="nav-icon fas fa-plus-square"></i>',
            'href' => '',
            'permissions' => ['drugstore_manage'],
            'children' => [
                [
                    'id' => 'menu-region',
                    'title' => 'Regions',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/region',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'drugstores',
                    'title' => 'All DrugStore',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/drugstore',
                    'permissions' => [],
                    'children' => [],
                ],

            ],
        ],
        [
            'id' => 'menu-agency',
            'title' => 'Agency',
            'icon' => '<i class="nav-icon fas fa-binoculars"></i>',
            'href' => '',
            'permissions' => ['post_manage'],
            'children' => [
                [
                    'id' => '',
                    'title' => 'Province',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/province',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => '',
                    'title' => 'Danh sách đại lý',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/agency',
                    'permissions' => [],
                    'children' => [],
                ],

            ],
        ],
        [
            'id' => 'menu-tool',
            'title' => 'Tools',
            'icon' => '<i class="nav-icon fas fa-tools"></i>',
            'href' => '',
            'permissions' => ['super_admin'],
            'children' => [
                [
                    'id' => 'fake-post',
                    'title' => 'Post',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/faker/post/auto',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'fake-ques',
                    'title' => 'Question',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/faker/question/auto',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'upgrade',
                    'title' => 'Upgrade',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/upgrade',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => 'replace-domain',
                    'title' => 'Replace-domain',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/upgrade/replace',
                    'permissions' => [],
                    'children' => [],
                ],

            ],
        ],
        [
            'id' => 'menu-crawler',
            'title' => 'Crawler',
            'icon' => '<i class="nav-icon fas fa-binoculars"></i>',
            'href' => '',
            'permissions' => ['super_admin'],
            'children' => [
                [
                    'id' => '',
                    'title' => 'Profile',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/crawlerProfile',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => '',
                    'title' => 'Crawl Handword',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/crawler',
                    'permissions' => [],
                    'children' => [],
                ],

            ],
        ],
        [
            'id' => 'menu-english',
            'title' => 'English App',
            'icon' => '<i class="fas fa-seedling"></i>',
            'href' => '',
            'permissions' => ['super_admin'],
            'children' => [
                [
                    'id' => '',
                    'title' => 'Configs',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/english-app-config',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => '',
                    'title' => 'Topic',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/topic-english',
                    'permissions' => [],
                    'children' => [],
                ],
                [
                    'id' => '',
                    'title' => 'Audio',
                    'icon' => 'fa-building-o',
                    'href' => '/admin/audio-english',
                    'permissions' => [],
                    'children' => [],
                ],

            ],
        ],
    ],
];
