<?php

return [
    'taxonomy' => [
        'category' => 'category',
        'tag' => 'tag',
        'menugroup' => 'menugroup',
        'albumgroup' => 'albumgroup',
        'videogroup' => 'videogroup',
        'questiongroup' => 'questiongroup',
        'province' => 'province',
        'region' => 'region',
        'brand' => 'brand',
        'productgroup' => 'productgroup',
        'lang' => 'lang',
        'buildprojectgroup' => 'buildprojectgroup',
    ],
    'taxonmyTmp' => [
        'tmp1' => 'tmp1',
        'tmp2' => 'tmp2',
        'tmp3' => 'tmp3',
        'tmp4' => 'tmp4',
        'tmp5' => 'tmp5',
    ],
    'taxonomyView' => [
        'category' => 'phobrv::term.category',
        'tag' => 'phobrv::term.tag',
        'menugroup' => 'phobrv::term.menugroup',
        'albumgroup' => 'phobrv::term.albumgroup',
        'videogroup' => 'phobrv::term.videogroup',
        'questiongroup' => 'phobrv::term.questiongroup',
        'region' => 'phobrv::term.region',
        'province' => 'phobrv::agency.province',
        'brand' => 'phobrv::term.brand',
        'productgroup' => 'phobrv::term.productgroup',
        'lang' => 'phobrv::term.lang',
        'buildprojectgroup' => 'phobrv::term.buildprojectgroup',
    ],
    'taxonomyLabel' => [
        'menugroup' => 'Menus',
        'category' => 'Category Post',
        'tag' => 'Tags',
        'albumgroup' => 'Albums',
        'videogroup' => 'Videos',
        'questiongroup' => 'Questions',
        'region' => 'Regions',
        'province' => 'Province',
        'productgroup' => 'Product Group',
        'brand' => 'Brand',
        'buildprojectgroup' => 'Build Project Group',
    ],
];
